---
-
  lineinfile: |
    dest=/etc/php7/apache2/php.ini
    regexp='date.timezone ='
    line='date.timezone = {{ server.timezone }}'
  name: "ensure timezone is set in apache2 php.ini"
-
  lineinfile: "dest=/etc/php7/apache2/php.ini regexp=';?opcache.enable=\\d' line='opcache.enable=1'"
  name: "enabling opcache"
